export const courseList = {
  code: 0,
  msg: '成功',
  data: {
    mainInfo: {
      weekCount: 20,
      curWeek: 11,
      curDayIndex: 5,
      semesterStartDate: '2022-02-27',
    },
    lessons: [
      {
        id: 374305,
        courseName: '形势与政策（2）',
        detailInfo: {
          adminClass: '电信科21-2班,计算机21-1班,计算机21-2班,计算机21-3班',
          studentCount: 178,
          credits: '0.25',
          courseTypeName: '通识必修课',
          code: '1201121B--013',
          weeks: '5~8周',
          examMode: '考查',
          teachers: [
            '陈秋凤',
          ],
        },
      },
      {
        id: 374313,
        courseName: '大学物理B（上）',
        detailInfo: {
          adminClass: '交通工程（中外合作）21-1班,机械工程（中外合作）21-1班,电信科21-1班,电信科21-2班',
          studentCount: 120,
          credits: '3',
          courseTypeName: '通识必修课',
          code: '1000231B--007',
          weeks: '4~15周',
          examMode: '笔试',
          teachers: [
            '王雅萍',
          ],
        },
      },
      {
        id: 374320,
        courseName: 'Python数据分析与可视化',
        detailInfo: {
          adminClass: '电信科21-2班',
          studentCount: 44,
          credits: '2',
          courseTypeName: '各专业选修课',
          code: '0540080X--002',
          weeks: '1~12周',
          examMode: '其他',
          teachers: [
            '冷金麟',
          ],
        },
      },
      {
        id: 374322,
        courseName: '电路分析基础',
        detailInfo: {
          adminClass: '电信科21-1班,电信科21-2班,电信科21-3班',
          studentCount: 158,
          credits: '3',
          courseTypeName: '学科基础和专业必修课',
          code: '0549832B--001',
          weeks: '1~11周',
          examMode: '笔试',
          teachers: [
            '李春华',
          ],
        },
      },
      {
        id: 374325,
        courseName: 'Java技术',
        detailInfo: {
          adminClass: '电信科21-1班,电信科21-2班,电信科21-3班',
          studentCount: 156,
          credits: '2',
          courseTypeName: '各专业选修课',
          code: '0509820X--004',
          weeks: '1~6周',
          examMode: '笔试',
          teachers: [
            '张延孔',
          ],
        },
      },
      {
        id: 374328,
        courseName: '数据结构与算法',
        detailInfo: {
          adminClass: '电信科21-1班,电信科21-2班,电信科21-3班',
          studentCount: 156,
          credits: '3',
          courseTypeName: '各专业选修课',
          code: '0539940X--001',
          weeks: '10~18周',
          examMode: '笔试',
          teachers: [
            '吕俊伟',
          ],
        },
      },
      {
        id: 374367,
        courseName: '线性代数',
        detailInfo: {
          adminClass: '电信科21-1班,电信科21-2班,计算机21-4班,计算机21-5班',
          studentCount: 178,
          credits: '2.5',
          courseTypeName: '通识必修课',
          code: '1400071B--013',
          weeks: '1~10周',
          examMode: '笔试',
          teachers: [
            '李杰',
          ],
        },
      },
      {
        id: 374686,
        courseName: '大学英语（2）',
        detailInfo: {
          adminClass: '电信科二级2班',
          studentCount: 32,
          credits: '2',
          courseTypeName: '通识必修课',
          code: '1500271B--028',
          weeks: '3~18周',
          examMode: '笔试',
          teachers: [
            '陈路林',
          ],
        },
      },
      {
        id: 374792,
        courseName: '高等数学A（下）',
        detailInfo: {
          adminClass: '电信科21-1班,电信科21-2班,经济学21-1班,经济学21-2班',
          studentCount: 183,
          credits: '6',
          courseTypeName: '通识必修课',
          code: '1400221B--002',
          weeks: '1~16周',
          examMode: '笔试',
          teachers: [
            '李彤',
          ],
        },
      },
      {
        id: 382550,
        courseName: '西方电影赏析',
        detailInfo: {
          adminClass: '公选课-002',
          studentCount: 200,
          credits: '1.5',
          courseTypeName: '公选-文化、语言与文学',
          code: '1519772X--002',
          weeks: '',
          examMode: '考查',
          teachers: [
            '赵伟兴',
          ],
        },
      },
      {
        id: 384300,
        courseName: '大学语文',
        detailInfo: {
          adminClass: '环境生态工程21-1班,电信科21-1班,电信科21-2班,食品质量与安全21-3班.物流21-1',
          studentCount: 217,
          credits: '2',
          courseTypeName: '其他',
          code: '5202012B--009',
          weeks: '1~8周',
          examMode: '笔试',
          teachers: [
            '祁高飞',
          ],
        },
      },
      {
        id: 384306,
        courseName: '大学体育（2）',
        detailInfo: {
          adminClass: '电信科21--1,2,3，经济21-1,2',
          studentCount: 32,
          credits: '0.5',
          courseTypeName: '通识必修课',
          code: '5100151B--020',
          weeks: '2~19周',
          examMode: '其他',
          teachers: [
            '柳毅',
          ],
        },
      },
      {
        id: 384520,
        courseName: '中国近现代史纲要',
        detailInfo: {
          adminClass: '电信科21-1班,电信科21-2班,网络与新媒体21-2班',
          studentCount: 127,
          credits: '3',
          courseTypeName: '通识必修课',
          code: '1201201B--016',
          weeks: '12~19周',
          examMode: '笔试',
          teachers: [
            '高磊',
            '王天云',
          ],
        },
      },
      {
        id: 384601,
        courseName: '法国文化',
        detailInfo: {
          adminClass: '公选课-001',
          studentCount: 200,
          credits: '1',
          courseTypeName: '公选-文化、语言与文学',
          code: '1502062X--001',
          weeks: '3~10周',
          examMode: '考查',
          teachers: [
            '夏然',
          ],
        },
      },
    ],
    schedule: [
      [
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂201',
            lessonIndex: 2,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂320',
            lessonIndex: 4,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂320',
            lessonIndex: 4,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂201',
            lessonIndex: 2,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '新安学堂316',
            lessonIndex: 4,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂118',
            lessonIndex: 4,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂201',
            lessonIndex: 2,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '新安学堂316',
            lessonIndex: 4,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
          {
            type: 'course',
            from: '19:00',
            to: '20:50',
            room: '敬亭学堂220',
            lessonIndex: 13,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '机房411',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂118',
            lessonIndex: 4,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂201',
            lessonIndex: 2,
          },
          {
            type: 'course',
            from: '19:00',
            to: '21:50',
            room: '敬亭学堂218',
            lessonIndex: 9,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '新安学堂316',
            lessonIndex: 4,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
          {
            type: 'course',
            from: '19:00',
            to: '20:50',
            room: '敬亭学堂220',
            lessonIndex: 13,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂322',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂118',
            lessonIndex: 4,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂201',
            lessonIndex: 2,
          },
          {
            type: 'course',
            from: '19:00',
            to: '21:50',
            room: '敬亭学堂218',
            lessonIndex: 9,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '新安学堂316',
            lessonIndex: 4,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
          {
            type: 'course',
            from: '19:00',
            to: '20:50',
            room: '敬亭学堂220',
            lessonIndex: 13,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂322',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂118',
            lessonIndex: 4,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂220',
            lessonIndex: 0,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂201',
            lessonIndex: 2,
          },
          {
            type: 'course',
            from: '19:00',
            to: '21:50',
            room: '敬亭学堂218',
            lessonIndex: 9,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '新安学堂316',
            lessonIndex: 4,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
          {
            type: 'course',
            from: '19:00',
            to: '20:50',
            room: '敬亭学堂220',
            lessonIndex: 13,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂322',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂118',
            lessonIndex: 4,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂220',
            lessonIndex: 0,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂201',
            lessonIndex: 2,
          },
          {
            type: 'course',
            from: '19:00',
            to: '21:50',
            room: '敬亭学堂218',
            lessonIndex: 9,
          },
        ],
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
          {
            type: 'course',
            from: '19:00',
            to: '20:50',
            room: '敬亭学堂220',
            lessonIndex: 13,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂322',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '新安学堂512',
            lessonIndex: 3,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂220',
            lessonIndex: 0,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂201',
            lessonIndex: 2,
          },
          {
            type: 'course',
            from: '19:00',
            to: '21:50',
            room: '敬亭学堂218',
            lessonIndex: 9,
          },
        ],
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
          {
            type: 'course',
            from: '19:00',
            to: '20:50',
            room: '敬亭学堂220',
            lessonIndex: 13,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '机房411',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '新安学堂512',
            lessonIndex: 3,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂116',
            lessonIndex: 10,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂220',
            lessonIndex: 0,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂201',
            lessonIndex: 2,
          },
          {
            type: 'course',
            from: '19:00',
            to: '21:50',
            room: '敬亭学堂218',
            lessonIndex: 9,
          },
        ],
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
          {
            type: 'course',
            from: '19:00',
            to: '20:50',
            room: '敬亭学堂220',
            lessonIndex: 13,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂322',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '新安学堂512',
            lessonIndex: 3,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '19:00',
            to: '21:50',
            room: '敬亭学堂218',
            lessonIndex: 9,
          },
        ],
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
          {
            type: 'course',
            from: '19:00',
            to: '20:50',
            room: '敬亭学堂220',
            lessonIndex: 13,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂220',
            lessonIndex: 6,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂201',
            lessonIndex: 2,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂322',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '新安学堂512',
            lessonIndex: 3,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂201',
            lessonIndex: 2,
          },
          {
            type: 'course',
            from: '19:00',
            to: '21:50',
            room: '敬亭学堂218',
            lessonIndex: 9,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂512',
            lessonIndex: 3,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
        ],
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂322',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂201',
            lessonIndex: 2,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂228',
            lessonIndex: 12,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
        ],
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂322',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂218',
            lessonIndex: 12,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂228',
            lessonIndex: 12,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
        ],
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '机房411',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂218',
            lessonIndex: 12,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂228',
            lessonIndex: 12,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
        ],
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂322',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂218',
            lessonIndex: 12,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂228',
            lessonIndex: 12,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
        ],
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂322',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂218',
            lessonIndex: 12,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂322',
            lessonIndex: 1,
          },
        ],
        [],
        [],
      ],
      [
        [
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂228',
            lessonIndex: 12,
          },
        ],
        [
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂322',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂218',
            lessonIndex: 12,
          },
        ],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂226',
            lessonIndex: 8,
          },
        ],
        [],
        [],
      ],
      [
        [],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂228',
            lessonIndex: 12,
          },
        ],
        [],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '新安学堂322',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂218',
            lessonIndex: 12,
          },
        ],
        [],
        [],
        [],
      ],
      [
        [],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂228',
            lessonIndex: 12,
          },
        ],
        [],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '机房411',
            lessonIndex: 7,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂218',
            lessonIndex: 12,
          },
        ],
        [],
        [],
        [],
      ],
      [
        [],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '10:10',
            to: '12:00',
            room: '敬亭学堂228',
            lessonIndex: 12,
          },
        ],
        [],
        [
          {
            type: 'course',
            from: '08:00',
            to: '09:50',
            room: '风雨操场',
            lessonIndex: 11,
          },
          {
            type: 'course',
            from: '14:00',
            to: '15:50',
            room: '敬亭学堂316',
            lessonIndex: 5,
          },
          {
            type: 'course',
            from: '16:00',
            to: '17:50',
            room: '敬亭学堂218',
            lessonIndex: 12,
          },
        ],
        [],
        [],
        [],
      ],
      [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
      ],
    ],
  },
}
