export const CourseLayout = {
  result: {
    id: 62,
    nameZh: '宣城校区课表布局',
    nameEn: '62',
    enabled: true,
    bizTypes: [],
    defaultBizTypes: [],
    courseUnitList: [
      {
        nameZh: '第一节',
        nameEn: '1',
        indexNo: 1,
        startTime: 800,
        endTime: 850,
        dayPart: 'MORNING',
        color: '#ffffff',
        startTimeText: '08:00',
        endTimeText: '08:50',
        name: '第一节',
      },
      {
        nameZh: '第二节',
        nameEn: '2',
        indexNo: 2,
        startTime: 900,
        endTime: 950,
        dayPart: 'MORNING',
        color: '#ffffff',
        startTimeText: '09:00',
        endTimeText: '09:50',
        name: '第二节',
      },
      {
        nameZh: '第三节',
        nameEn: '3',
        indexNo: 3,
        startTime: 1010,
        endTime: 1100,
        dayPart: 'MORNING',
        color: '#ffffff',
        startTimeText: '10:10',
        endTimeText: '11:00',
        name: '第三节',
      },
      {
        nameZh: '第四节',
        nameEn: '4',
        indexNo: 4,
        startTime: 1110,
        endTime: 1200,
        dayPart: 'MORNING',
        color: '#ffffff',
        startTimeText: '11:10',
        endTimeText: '12:00',
        name: '第四节',
      },
      {
        nameZh: '第五节',
        nameEn: '5',
        indexNo: 5,
        startTime: 1400,
        endTime: 1450,
        dayPart: 'AFTERNOON',
        color: '#ffffff',
        startTimeText: '14:00',
        endTimeText: '14:50',
        name: '第五节',
      },
      {
        nameZh: '第六节',
        nameEn: '6',
        indexNo: 6,
        startTime: 1500,
        endTime: 1550,
        dayPart: 'AFTERNOON',
        color: '#ffffff',
        startTimeText: '15:00',
        endTimeText: '15:50',
        name: '第六节',
      },
      {
        nameZh: '第七节',
        nameEn: '7',
        indexNo: 7,
        startTime: 1600,
        endTime: 1650,
        dayPart: 'AFTERNOON',
        color: '#ffffff',
        startTimeText: '16:00',
        endTimeText: '16:50',
        name: '第七节',
      },
      {
        nameZh: '第八节',
        nameEn: '8',
        indexNo: 8,
        startTime: 1700,
        endTime: 1750,
        dayPart: 'AFTERNOON',
        color: '#ffffff',
        startTimeText: '17:00',
        endTimeText: '17:50',
        name: '第八节',
      },
      {
        nameZh: '第九节',
        nameEn: '9',
        indexNo: 9,
        startTime: 1900,
        endTime: 1950,
        dayPart: 'EVENING',
        color: '#ffffff',
        startTimeText: '19:00',
        endTimeText: '19:50',
        name: '第九节',
      },
      {
        nameZh: '第十节',
        nameEn: '10',
        indexNo: 10,
        startTime: 2000,
        endTime: 2050,
        dayPart: 'EVENING',
        color: '#ffffff',
        startTimeText: '20:00',
        endTimeText: '20:50',
        name: '第十节',
      },
      {
        nameZh: '第十一节',
        nameEn: '11',
        indexNo: 11,
        startTime: 2100,
        endTime: 2150,
        dayPart: 'EVENING',
        color: '#ffffff',
        startTimeText: '21:00',
        endTimeText: '21:50',
        name: '第十一节',
      },
    ],
  },
}
